name: Weekly Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          ./build.sh

      - name: switch branch
        run: |
          git checkout -b release
          rm -rf ./.github ./readme.md ./build.sh

      - name: push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Weekly Build'
          git push -f origin release
